/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abc;

import dbConnect.dbConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Ravindu Nimesh
 */
public class addmem extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    
    public addmem() {
        initComponents();
        
        con = dbConnect.connectprj();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fnamebox = new javax.swing.JTextField();
        lnamebox = new javax.swing.JTextField();
        tpnbox = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        addrbox = new javax.swing.JTextArea();
        sex1 = new javax.swing.JRadioButton();
        sex2 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(700, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date of birth");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 90, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 90, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Sex");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 25));
        getContentPane().add(fnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 265, -1));
        getContentPane().add(lnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 265, -1));
        getContentPane().add(tpnbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 265, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 76, -1));

        addrbox.setColumns(20);
        addrbox.setRows(5);
        jScrollPane1.setViewportView(addrbox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 175, 268, 70));

        sex1.setText("Male");
        sex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sex1ActionPerformed(evt);
            }
        });
        getContentPane().add(sex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        sex2.setText("Female");
        sex2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sex2ActionPerformed(evt);
            }
        });
        getContentPane().add(sex2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 61, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 60, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Select Package");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 25));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Bronze", "Silver", "Gold" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 89, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("paid registraion fee(1500 LKR)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, 25));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, -1, -1));

        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jLabel15.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        jLabel16.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        jLabel17.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        jLabel18.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        jLabel19.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 89, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sex1ActionPerformed
      gender="male";
    }//GEN-LAST:event_sex1ActionPerformed

    private void sex2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sex2ActionPerformed
    gender="female";
    }//GEN-LAST:event_sex2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        boolean b1=sex1.isSelected();
        boolean b2=sex2.isSelected();
        

       if(fnamebox.getText().isEmpty() || lnamebox.getText().isEmpty() || tpnbox.getText().isEmpty() || addrbox.getText().isEmpty() || (b1==false && b2==false)
       || (jComboBox2.getSelectedIndex()==0 || jComboBox3.getSelectedIndex()==0 || jComboBox4.getSelectedIndex()==0) || jComboBox5.getSelectedIndex()==0 ){
                JOptionPane.showMessageDialog(null,"Some Fields are empty.");      
        }
        else{
           
           String y=jComboBox2.getSelectedItem().toString();
           String m=jComboBox3.getSelectedItem().toString();
           String d=jComboBox4.getSelectedItem().toString();
           
           String fn=fnamebox.getText();
           String ln=lnamebox.getText();
           String ph=tpnbox.getText();
           String addr=addrbox.getText();
           String sex=gender;
           String dob=y+"/"+m+"/"+d; 
           String pac=jComboBox5.getSelectedItem().toString();
           String regf=jComboBox7.getSelectedItem().toString();
               

           try {
               String q = "insert into meminfo (fname,Lname,tpn,addr,sex,dob,package,regFee) values ('" +fn+ "','"+ln+"','"+ph+"','"+addr+"','"+sex+"','"+dob+"','"+pac+"','"+regf+"')";
               pst =con.prepareStatement(q);
               pst.execute();
               
                JOptionPane.showMessageDialog(null,"Successfull !!");      

           } 
           
           catch (Exception e) {
               System.err.println(e);
           }
        }
        

      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         ButtonGroup gp = new ButtonGroup();     
         //jTextField1.setText(null);
         fnamebox.setText(null);
         lnamebox.setText(null);
         tpnbox.setText(null);
         addrbox.setText(null);
         jComboBox2.setSelectedIndex(0);
         jComboBox3.setSelectedIndex(0);
         jComboBox4.setSelectedIndex(0);
         jComboBox5.setSelectedIndex(0);
         jComboBox7.setSelectedIndex(0);
         gp.add(sex1);
         gp.add(sex2);  
         gp.clearSelection();
         
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addrbox;
    private javax.swing.JTextField fnamebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnamebox;
    private javax.swing.JRadioButton sex1;
    private javax.swing.JRadioButton sex2;
    private javax.swing.JTextField tpnbox;
    // End of variables declaration//GEN-END:variables
    private String gender=null;
}
