/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abc;

import dbConnect.dbConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravindu Nimesh
 */
public class login extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        conn = dbConnect.connectprj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 250));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 50, 89, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 90, 89, 33);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(380, 60, 146, 20);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(380, 100, 146, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(427, 200, 77, 27);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Member", "Trainer" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(380, 140, 90, 20);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 87, 72, 0);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(406, 35, 72, 0);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Login as");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 130, 78, 33);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CloseButton.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(500, 10, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 550, 250);

        setSize(new java.awt.Dimension(550, 250));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        eror e=new eror();
        main m=new main();
        memberlogin mb=new memberlogin();
        Trainer tr=new Trainer();
        
        if(jTextField1.getText().isEmpty() || jPasswordField1.getPassword().equals("") || jPasswordField1.getPassword().length==0){
            e.setVisible(true);
         
        }
        else if(!jTextField1.getText().isEmpty() || !jPasswordField1.getPassword().equals(""))
        {
            
            int a=jComboBox1.getSelectedIndex();
            if(a==0){
               // username admin
                if(jTextField1.getText().contentEquals("admin")){
                //     password admin 
                    if(jPasswordField1.getPassword().length>3){   
                     m.setVisible(true);
                     this.dispose();
                    }
                    else{
                        String b="Invalid";
                        jLabel3.setText(b);
                    }
                }
                else{
                    String b="Invalid";
                    jLabel4.setText(b);
                    
                }
                
            }
            else if(a==1){
              //  username member
                if(jTextField1.getText().contentEquals("PGmember")){
               //     password member
                    if(jPasswordField1.getPassword().length>3 ){   
                     mb.setVisible(true);
                     this.dispose();
                    }
                    else{
                        String b="Invalid";
                        jLabel3.setText(b);
                    }
                }
                else {
                    String b="Invalid";
                    jLabel4.setText(b);
                }
                
            }
            else if(a==2){
                
              //  trainer member
                if(jTextField1.getText().contentEquals("PGtrainer")){
                //    password trainer
                
                    if(jPasswordField1.getPassword().length>3){   
                     tr.setVisible(true);
                     this.dispose();
                    }
                    else{
                        String b="Invalid";
                        jLabel3.setText(b);
                    }
                }
                else {
                    String b="Invalid";
                    jLabel4.setText(b);
                }
                
            }
 
        }
    }//GEN-LAST:event_jButton1ActionPerformed
        

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        int dialogButton = 0;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to quit?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
           this.dispose();
        
    }//GEN-LAST:event_jLabel7MouseClicked
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
