/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abc;

/**
 *
 * @author Pramesh
 */
public class pacdetails extends javax.swing.JFrame {

    /**
     * Creates new form pacdetails
     */
    public pacdetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("1.Gold Package");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(37, 172, 122, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("2.Silver Package");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(208, 172, 127, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("3.Bronze Package");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(373, 172, 138, 22);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("6 months duration");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(37, 212, 87, 14);

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("6 times per week");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(37, 232, 81, 14);

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Can use A,B areas");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(37, 252, 89, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("10000 LKR");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(37, 284, 77, 17);

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Can use A,B areas");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(208, 252, 89, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("8000 LKR");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(208, 284, 68, 17);

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("6 months duration");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(208, 212, 87, 14);

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("4 times per week");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(208, 232, 81, 14);

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Can'y use A area");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(373, 252, 82, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("6000 LKR");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(373, 284, 68, 17);

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("6 months duration");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(373, 212, 87, 14);

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("4 times per week");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(373, 232, 81, 14);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CloseButton.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(490, 10, 50, 50);

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PacDetails.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, -10, 550, 340);

        setSize(new java.awt.Dimension(542, 326));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        int dialogButton = 0;
        //int dialogResult = javax.swing.JOptionPane.showConfirmDialog (null, "Do you want to quit?","Warning",dialogButton);
        //if(dialogResult == javax.swing.JOptionPane.YES_OPTION){
           this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pacdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pacdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pacdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pacdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pacdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
