/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abc;

import dbConnect.dbConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Malik
 */
public class Trainer extends javax.swing.JFrame {
   Connection con = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form Trainer
     */
    public Trainer() {
        initComponents();
        
        con = dbConnect.connectprj();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("MemID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 100, 108, 28);

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Squat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 120, 108, 28);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Bench Press");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 170, 108, 28);

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Front Press");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 200, 108, 28);

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Back Press");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 240, 108, 28);

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Full Over");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 270, 43, 28);

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Tricep");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 310, 59, 28);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(490, 100, 220, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(490, 130, 220, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(490, 170, 220, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(490, 200, 220, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(490, 240, 220, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(490, 270, 220, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(490, 310, 220, 20);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 370, 98, 52);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 370, 98, 52);

        jButton3.setText("Check Schedule");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 370, 110, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CloseButton.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(677, 20, 40, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogOutButton.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 20, 65, 57);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trainer.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 730, 460);

        setSize(new java.awt.Dimension(727, 462));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTextField1.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() ||jTextField5.getText().isEmpty() || jTextField6.getText().isEmpty()|| jTextField7.getText().isEmpty()
          ||jTextField8.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Error!!! Some fields are empty");      
        }
        else{
           
        
           
           String mid=jTextField1.getText();
           String sqt=jTextField3.getText();
           String bnch=jTextField4.getText();
           String frnt=jTextField5.getText();
           String back=jTextField6.getText();
           String ful=jTextField7.getText();
           String tri=jTextField8.getText();
               

           try {
               String q = "insert into workoutinfo (memID,Squat,Bench,Front,Back,Full,Tri) values ('" +mid+ "','"+sqt+"','"+bnch+"','"+frnt+"','"+back+"','"+ful+"','"+tri+"')";
               pst =con.prepareStatement(q);
               pst.execute();
               
                JOptionPane.showMessageDialog(null,"Successfull !!");      

           } 
           
           catch (Exception e) {
               System.err.println(e);
           }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           jTextField1.setText(null);
           jTextField3.setText(null);
           jTextField4.setText(null);
           jTextField5.setText(null);
           jTextField6.setText(null);
           jTextField7.setText(null);
           jTextField8.setText(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int dialogButton = 0;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to quit?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
           this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
    }
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       
   login l=new login();
        int dialogButton = 0;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to logout?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            l.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_jLabel9MouseClicked
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        checksh ck= new checksh();
        ck.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
